import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-government-grant-drawdown-reimbursement",
  "engine": "recovery",
  "title": "Government Grant Drawdown & Reimbursement",
  "shortTitle": "Grant Cash Recovery",
  "tagline": "Convert allowable project costs into timely, compliant grant cash",
  "industry": "Public Funding Post-Award Finance",
  "uiPort": 4564,
  "apiPort": 5564,
  "accent": "#0369a1",
  "currency": "USD",
  "primaryOutcome": "Allowable grant expenditures drawn down and reimbursed without compliance leakage",
  "valueNarrative": "Connect awards, budgets, cost principles, payroll, procurement, subawards, milestones, payment systems, and cash receipts.",
  "calculation": {
    "actualKey": "receivedDraw",
    "expectedKey": "eligibleDraw",
    "actualLabel": "Cash received",
    "expectedLabel": "Eligible reimbursement",
    "varianceLabel": "Undrawn eligible funding",
    "direction": "expected-minus-actual",
    "finding": "Award, expenditure, milestone, and allowability evidence indicate eligible but undrawn grant reimbursement.",
    "actions": [
      "Reconcile expenditures to award budget and cost principles",
      "Validate payroll, procurement, subaward, and match evidence",
      "Prepare the payment request and supporting schedules",
      "Track agency review and reconcile cash receipt"
    ]
  }
},[
feature("award-and-amendment-library","GCR01","Award and amendment library","Reconcile award and amendment library using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed award and amendment library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("budget-and-funding-source-control","GCR02","Budget and funding-source control","Reconcile budget and funding-source control using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed budget and funding-source control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("expenditure-ingestion-and-mapping","GCR03","Expenditure ingestion and mapping","Reconcile expenditure ingestion and mapping using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed expenditure ingestion and mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("cost-allowability-validation","GCR04","Cost allowability validation","Reconcile cost allowability validation using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed cost allowability validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("payroll-and-time-effort-support","GCR05","Payroll and time-effort support","Reconcile payroll and time-effort support using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed payroll and time-effort support decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("procurement-compliance-evidence","GCR06","Procurement compliance evidence","Reconcile procurement compliance evidence using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed procurement compliance evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("subrecipient-cost-validation","GCR07","Subrecipient cost validation","Reconcile subrecipient cost validation using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed subrecipient cost validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("match-and-cost-share-tracking","GCR08","Match and cost-share tracking","Reconcile match and cost-share tracking using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed match and cost-share tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("program-income-accounting","GCR09","Program income accounting","Reconcile program income accounting using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed program income accounting decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("milestone-and-deliverable-tracking","GCR10","Milestone and deliverable tracking","Reconcile milestone and deliverable tracking using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed milestone and deliverable tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("drawdown-calculation","GCR11","Drawdown calculation","Reconcile drawdown calculation using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed drawdown calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("payment-request-package","GCR12","Payment request package","Reconcile payment request package using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed payment request package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("agency-query-and-correction-workflow","GCR13","Agency query and correction workflow","Reconcile agency query and correction workflow using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed agency query and correction workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("cash-receipt-reconciliation","GCR14","Cash receipt reconciliation","Reconcile cash receipt reconciliation using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed cash receipt reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]}),
feature("award-utilization-and-forecast-analytics","GCR15","Award utilization and forecast analytics","Reconcile award utilization and forecast analytics using award documents, approved budgets, 2 CFR 200 controls, payroll, procurement, subawards, milestones, payment requests, and cash.","Produce a governed award utilization and forecast analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["agency","Funding Agency","text","Department of Infrastructure"],["awardPeriod","Award / Period","text","INFRA-2025-184 / Q2"],["receivedDraw","Cash Received","currency",1280000],["eligibleDraw","Eligible Reimbursement","currency",1645000]],{amountField:"receivedDraw",subjects:["Infrastructure grant","Research grant","Workforce development award","Climate resilience award","Public health cooperative agreement"]})
]);
